### ISSUE TITLE
jq is required in kyma-k3d.sh

### ISSUE THREAD

**Issue by moepser** [kyma-incubator/local-kyma#46]
Hi,

seems like jq is required during installation? Could you update the install script to check for it?
Sorry if I am wrong I am new to this ;)

**Comment by pbochynski** [comment]
Yes you need jq. I will update the documentation.

**Comment by pbochynski** [comment]
The prerequisites are updated. I'd rather avoid additional lines for checking dependencies as I want to keep the script short.
