### ISSUE TITLE
Failed to install components via helm

### ISSUE THREAD

**Issue by lanphan** [kyma-incubator/local-kyma#77]
When running `./kyma-k3d.sh`, I see that there are lots of error logs relating to installation below. It seems that helm repo is not up-to-dated? Please help to check and update, thanks (sorry that I don't know about this one to contribute PR). Noted that my script still completes successfully even getting these errors (pass all tests and I can access https://console.local.kyma.dev)

> Release "core" does not exist. Installing it now.
> Release "helm-broker" does not exist. Installing it now.
> Release "service-catalog" does not exist. Installing it now.
> Release "service-catalog-addons" does not exist. Installing it now.
> Release "logging" does not exist. Installing it now.
> Release "pod-preset" does not exist. Installing it now.
> Release "monitoring" does not exist. Installing it now.
> Release "dex" does not exist. Installing it now.
> Release "cluster-users" does not exist. Installing it now.
> Release "tracing" does not exist. Installing it now.
> Release "application-connector" does not exist. Installing it now.
> Release "rafter" does not exist. Installing it now.
> Release "event-sources" does not exist. Installing it now.
> Release "ory" does not exist. Installing it now.
> Error: failed to download "resources/event-sources" (hint: running `helm repo update` may help)
> Release "knative-provisioner-natss" does not exist. Installing it now.
> Error: failed to download "resources/knative-provisioner-natss" (hint: running `helm repo update` may help)
> Release "ingress-dns-cert" does not exist. Installing it now.
> load.go:120: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
> Release "api-gateway" does not exist. Installing it now.
> Release "kiali" does not exist. Installing it now.
> Release "knative-eventing" does not exist. Installing it now.
> Release "nats-streaming" does not exist. Installing it now.
> Error: failed to download "resources/knative-eventing" (hint: running `helm repo update` may help)
> Error: failed to download "resources/nats-streaming" (hint: running `helm repo update` may help)
> Release "serverless" does not exist. Installing it now.
> Release "console" does not exist. Installing it now.
> Installing event-sources in the namespace kyma-system
> Installing knative-provisioner-natss in the namespace knative-eventing
> Installing nats-streaming in the namespace natss
> Installing knative-eventing in the namespace knative-eventing
> Release "event-sources" does not exist. Installing it now.
> Error: failed to download "resources/event-sources" (hint: running `helm repo update` may help)
> Release "knative-provisioner-natss" does not exist. Installing it now.
> Error: failed to download "resources/knative-provisioner-natss" (hint: running `helm repo update` may help)
> Release "nats-streaming" does not exist. Installing it now.
> Error: failed to download "resources/nats-streaming" (hint: running `helm repo update` may help)
> Release "knative-eventing" does not exist. Installing it now.
> Error: failed to download "resources/knative-eventing" (hint: running `helm repo update` may help)
> Installing knative-provisioner-natss in the namespace knative-eventing
> Installing nats-streaming in the namespace natss
> Installing event-sources in the namespace kyma-system
> Installing knative-eventing in the namespace knative-eventing
> Release "nats-streaming" does not exist. Installing it now.
> Error: failed to download "resources/nats-streaming" (hint: running `helm repo update` may help)
> Release "knative-provisioner-natss" does not exist. Installing it now.
> Error: failed to download "resources/knative-provisioner-natss" (hint: running `helm repo update` may help)
> Release "event-sources" does not exist. Installing it now.
> Error: failed to download "resources/event-sources" (hint: running `helm repo update` may help)
> Release "knative-eventing" does not exist. Installing it now.
> Error: failed to download "resources/knative-eventing" (hint: running `helm repo update` may help)
> Installing nats-streaming in the namespace natss
> Installing knative-provisioner-natss in the namespace knative-eventing
> Installing event-sources in the namespace kyma-system
> Installing knative-eventing in the namespace knative-eventing
> Release "nats-streaming" does not exist. Installing it now.
> Error: failed to download "resources/nats-streaming" (hint: running `helm repo update` may help)
> Release "knative-provisioner-natss" does not exist. Installing it now.
> Error: failed to download "resources/knative-provisioner-natss" (hint: running `helm repo update` may help)
> namespace/kyma-installer created
> Release "event-sources" does not exist. Installing it now.
> Error: failed to download "resources/event-sources" (hint: running `helm repo update` may help)
> deployment.apps/kyma-installer created
> Waiting for 20 command(s) executed in the background, elapsed time: 0 min 12 sec
> Release "knative-eventing" does not exist. Installing it now.
> Error: failed to download "resources/knative-eventing" (hint: running `helm repo update` may help)

**Comment by lanphan** [comment]
Noted that on my PC, there is no repo configured for helm:

> lanphan@Lans-MacBook-Pro onex-passport % helm repo list
> Error: no repositories to show

**Comment by pbochynski** [comment]
The script is installing helm releases from the local folder. You need to first download kyma charts.

**Comment by lanphan** [comment]
Hi @pbochynski ,

Definitely I did run script `./download-kyma-charts.sh` before, please check image my local-kyma folder, there is `resources/` folder there

<img width="622" alt="Screen Shot 2021-04-29 at 18 42 45" src="https://user-images.githubusercontent.com/360654/116545579-d142ec80-a91a-11eb-9049-ce78fc4a7b01.png">

Please help to check and re-open if it's valid.

**Comment by lanphan** [comment]
https://github.com/kyma-project/kyma/tree/main/resources

Random check that, content of resources/ folder in kyma-project/kyma doesn't have `nats-streaming` folder
