### ISSUE TITLE
How to log into Console after restart k3d?

### ISSUE THREAD

**Issue by lanphan** [kyma-incubator/local-kyma#79]
I did see that there is script `./kyma-k3d-start.sh` , therefore I think I can stop it by using
`k3d cluster stop kyma`

Somehow it works (without error), but I cannot log into Console.
Is there anyway I can do to refresh token / refresh password so that I can log into Console after restart k3d?

Thanks.

**Comment by pbochynski** [comment]
Probably you need to wait a bit for console/dex to be restarted. Are all pods in kyma-system namespace healthy?
