### ISSUE TITLE
Ory release fails frequently

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/local-kyma#8]
Ory release is the slowest one from all charts in Kyma, and fails frequently. In this case helm reported an error:
> Error: failed post-install: warning: Hook post-install ory/charts/oathkeeper/templates/job.yaml failed: Internal error occurred: failed calling webhook "legacysinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/legacysinkbindings?timeout=10s: dial tcp 10.43.239.58:443: connect: connection refused

**Comment by nachtmaar** [comment]
I could reproduce it. For me the rafter chart failed. It did see the following error in the knative-eventing webhook:
```
{
  "level": "error",
  "ts": "2020-07-30T11:44:38.598Z",
  "logger": "eventing-webhook",
  "caller": "controller/controller.go:376",
  "msg": "Reconcile error",
  "commit": "8a92a8c",
  "error": "secret \"eventing-webhook-certs\" is missing \"ca-cert.pem\" key",
  "stacktrace": "knative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\t/home/prow/go/src/knative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:376\nknative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/home/prow/go/src/knative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:362\nknative.dev/eventing/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\t/home/prow/go/src/knative.dev/eventing/vendor/knative.dev/pkg/controller/controller.go:310"
}
```

A possible explanation: All charts are installed in parallel. That means as soon as the knative-eventing chart gets installed it registers the webhook (for sinkbindings which basically intercepts all v1 resources mutations), but at the same time the webhook is not ready (see error message, it is waiting for the certificate).

Another retry of the failed chart solved the issue.

The linked PR however, should enable a race-free parallel installation.

**Comment by pbochynski** [comment]
I didn't observe this problem since PR was merged. Thanks @nachtmaar !
