### ISSUE TITLE
Cannot login Console after hibernating (k3d)

### ISSUE THREAD

**Issue by lanphan** [kyma-incubator/local-kyma#80]
There is a guideline about this problem with minikube here:
https://kyma-project.io/docs/#troubleshooting-basic-troubleshooting-can-t-log-in-to-the-console-after-hibernating-the-minikube-cluster

<img width="780" alt="Screen Shot 2021-04-29 at 10 36 13" src="https://user-images.githubusercontent.com/360654/116499655-e72ebe00-a8d6-11eb-822c-edc409f83c1f.png">

Do I need to do the same in k3d? Which command should I run?

Thanks.

**Comment by pbochynski** [comment]
I didn't face such problems with hibernation and k3d. But sometimes coredns patch is reverted and console cannot reach some URLs (e.g. dex). The solution is to execute this script: https://github.com/kyma-incubator/local-kyma/blob/main/kyma-k3d-start.sh
